### ISSUE TITLE
invalid subscript type 'list'

### ISSUE THREAD

**Issue by giacom0rovers1** [overeem11/RAINLINK#1]
Hi,
I tried to run the RAINLINK package launching the 'Run.R' script after reading the Manual files and the Overeem et al. 2016 article. The program execution halts during the 'RainMapsRadarsTimeStep' function with the error message that follows:
`Error in ScaleLow[p] : invalid subscript type 'list'
Calls: RainMapsRadarsTimeStep ... by_layer -> f -> <Anonymous> -> f -> lapply -> FUN -> eval`
The corresponding figure is blank.
I tried too look at the code for some debugging but I am not R expert.

That's the output from R CMD BATCH Run.R (I added the .txt extension for the upload)

[Run.Rout.txt](https://github.com/overeem11/RAINLINK/files/449424/Run.Rout.txt)

Thanks
Giacomo Roversi

**Comment by overeem11** [comment]
Dear Giacomi,

Thanks for your interest in our package!

I also recently discovered this error when I ran RAINLINK on the newest R version. This is probably related to the use of a newer R version, although I don't understand why this error pops up. I believe that the problem should disappear when you load two additional R packages: "digest" and "RColorbrewer". Please let me know whether that solves the problem. Unfortunately, I'm not available the coming three weeks (holidays). There will be a new version of RAINLINK somewhere the coming months, where I will add these two packages in the Config.R file.

If this works, you will probably encounter another problem, i.e. that the color scale will differ from the one used in our paper. Please let me know whether that is the case, than I can at least provide you with an example R script how to solve this (solution is very simple, but hard to find). Unfortunately, R functions do not always seem to work stable for different R versions and debugging is certainly not straightforward.

Best,

Aart

Aart Overeem
Royal Netherlands Meteorological Institute / Wageningen University

---

Van: Giacomo Roversi [notifications@github.com]
Verzonden: donderdag 1 september 2016 12:58
Aan: overeem11/RAINLINK
Onderwerp: [overeem11/RAINLINK] invalid subscript type 'list' (#1)

Hi,
I tried to run the RAINLINK package launching the 'Run.R' script after reading the Manual files and the Overeem et al. 2016 article. The program execution halts during the 'RainMapsRadarsTimeStep' function with the error message that follows:
Error in ScaleLow[p] : invalid subscript type 'list'
Calls: RainMapsRadarsTimeStep ... by_layer -> f -> <Anonymous> -> f -> lapply -> FUN -> eval
The corresponding figure is blank.
I tried too look at the code for some debugging but I am not R expert.

That's the output from R CMD BATCH Run.R (I added the .txt extension for the upload)

Run.Rout.txthttps://github.com/overeem11/RAINLINK/files/449424/Run.Rout.txt

Thanks
Giacomo Roversi

�

**Comment by giacom0rovers1** [comment]
Dear Aart
Thank you very much for the immediate and kind answer.
The fix with the new libraries does not seem to work for now, but the processing is quite slow and I need more runs to be sure, I keep testing and I let you know. 

Do you think that a temporary R downgrad could be a good solution?

By the way, I am a master student at the Alma Mater Studiorum University of Bologna and I am collaborating with Stefania Passetti and MEEO.it on the implementation of RAINLINK over the local microwave network here in Emilia Romagna (Italy). 

Thank you again, 

Giacomo Roversi 
Ferrara (Italy)

P.S. I have another observation but I open a new issue for clearness.

**Comment by giacom0rovers1** [comment]
I downgraded R and all the packages at the 3.3.0 (2016-05-03) which is the oldest I can recover with the dnf downgrade option (I run the fedora 24 linux distro).
It seems that the bug persists. I'll go back to 3.3.1
I'm sorry I can not help you for the moment

best regards
Giacomo

**Comment by overeem11** [comment]
Dear Giacomo Roversi,

Very nice that you are working with RAINLINK using Italian microwave link data! As far as I know you are the first group which actually uses this package.

Two of our PhD students will start to work with RAINLINK the coming months. The plan is to add functionality, to also be able to process data from networks with instantaneous measurements. I will only give a small update of RAINLINK within a couple of months, mainly improving the documentation and removing some errors, as discussed.

Thanks,
Aart

---

Van: Giacomo Roversi [notifications@github.com]
Verzonden: donderdag 1 september 2016 15:17
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Comment
Onderwerp: Re: [overeem11/RAINLINK] invalid subscript type 'list' (#1)

Dear Aart
Thank you very much for the immediate and kind answer.
The fix with the new libraries does not seem to work for now, but the processing is quite slow and I need more runs to be sure, I keep testing and I let you know.

Do you think that a temporary R downgrad could be a good solution?

By the way, I am a master student at the Alma Mater Studiorum University of Bologna and I am collaborating with Stefania Passetti and MEEO.it on the implementation of RAINLINK over the local microwave network here in Emilia Romagna (Italy).

Thank you again,

Giacomo Roversi
Ferrara (Italy)

P.S. I have another observation but I open a new issue for clearness.

�

**Comment by overeem11** [comment]
Strange. I suggest you try a modified version of the Config.R file and RainMapsRadarsTimeStep.R. I just tested this at my Fedora 24 machine with R 3.3.1 ... And I've added some commands to the function, which solve the color scale problem I mentioned before. So this should work ...

#############################

# 8.3 RainMapsRadarsTimeStep

#############################

# Name and path of daily radar input file:

# NetCDF4 file for daily rainfall depths:

# Download from Climate4Impact (works at least for Linux):

# path <- "http://opendap.knmi.nl/knmi/thredds/fileServer/radarprecipclim/RAD_NL25_RAC_MFBS_24H_NC/2011/09/RAD_NL25_RAC_MFBS_24H_201109110800.nc"

# Path in NetCDF4 file with radar data:

PathRadarRainfallDepth <- "image1_image_data"

# Name of folder which contains 5-min radar rainfall files

FolderRadarRainMapsTimeStep <- "Radar5min"

# Run function RainMapsRadarsTimeStep:

RainMapsRadarsTimeStep(AlphaPlotLocation=AlphaPlotLocation,AlphaPolygon=AlphaPolygon,AlphaScale=AlphaScale,
AutDefineLegendTop=AutDefineLegendTop,BBoxOSMauto=BBoxOSMauto,ColoursNumber=ColoursNumber,ColourPlotLocation=ColourPlotLocation,
ColourPlotLocationText=ColourPlotLocationText,ColourType=ColourType,ColourHighestClass=ColourHighestClass,
CoorSystemInputData=CoorSystemInputData,Direction=Direction,ExtraDeg=ExtraDeg,ExtraText=ExtraText,FigFileRadarsTimeStep=FigFileRadarsTimeStep,FigHeight=FigHeight,
FigWidth=FigWidth,FileGrid=FileGrid,FilePolygonsGrid=FilePolygonsGrid,FolderFigures=FolderFigures,FolderRadarRainMapsTimeStep=FolderRadarRainMapsTimeStep,
FontFamily=FontFamily,GoogleLocDegSpecified=GoogleLocDegSpecified,GoogleLocLat=GoogleLocLat,
GoogleLocLon=GoogleLocLon,GoogleLocName=GoogleLocName,GoogleLocNameSpecified=GoogleLocNameSpecified,GoogleMapType=GoogleMapType,GoogleZoomlevel=GoogleZoomlevel,
LabelAxisLat=LabelAxisLat,LabelAxisLonGoogle=LabelAxisLonGoogle,LabelAxisLonOSM=LabelAxisLonOSM,LatLocation=LatLocation,LatText=LatText,
LegendTitleRadarsTimeStep=LegendTitleRadarsTimeStep,LonLocation=LonLocation,LonText=LonText,ManualScale=ManualScale,MapBackground=MapBackground,
OSMBottom=OSMBottom,OSMLeft=OSMLeft,OSMRight=OSMRight,OSMScale=OSMScale,OSMTop=OSMTop,Palette=Palette,PathRadarRainfallDepth=PathRadarRainfallDepth,
PERIOD=PERIOD,PlotLocation=PlotLocation,PixelBorderCol=PixelBorderCol,PlotBelowScaleBottom=PlotBelowScaleBottom,ReverseScale=ReverseScale,
ScaleBottomTimeStep=ScaleBottomTimeStep,ScaleHigh=ScaleHigh,ScaleLow=ScaleLow,ScaleTopTimeStep=ScaleTopTimeStep,SizePixelBorder=SizePixelBorder,
SizePlotLocation=SizePlotLocation,SizePlotTitle=SizePlotTitle,SymbolPlotLocation=SymbolPlotLocation,TIMESTEP=TIMESTEP,TimeZone=TimeZone,TitleRadars=TitleRadars,XMiddle=XMiddle,
YMiddle=YMiddle)

Best,
Aart

---

Van: Giacomo Roversi [notifications@github.com]
Verzonden: donderdag 1 september 2016 16:46
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Comment
Onderwerp: Re: [overeem11/RAINLINK] invalid subscript type 'list' (#1)

I downgraded R and all the packages at the 3.3.0 (2016-05-03) which is the oldest I can recover with the dnf downgrade option (I run the fedora 24 linux distro).
It seems that the bug persists. I'll go back to 3.3.1
I'm sorry I can not help you for the moment

best regards
Giacomo

**Comment by giacom0rovers1** [comment]
Dear Aart
Wonderful! We too will be interested in real-time measures.
Let's keep in touch and again thank you
Giacomo

**Comment by giacom0rovers1** [comment]
Ok nice 
I'll try this!

**Comment by giacom0rovers1** [comment]
Sorry for the multiple messages.
I have copied the code in the corresponding section of Run.R, but I do not have received any modified copy of Config.R or RainMapsRadarsTimeStep.R. Do I have to edit them with this informations or were they meant to be forwarded with the post?
Thank you for your time
Giacomo

**Comment by overeem11** [comment]
I attached these two files to the e-mail, apparently that does not work. Can I send it to an e-mail address?

By the way, what I meant with “instanteneous” was related to the sampling strategy, i.e. not min/max over 15 min, but e.g. one value every 15 min.

Note that I will only look at my e-mail coming Saturday and then I will not respond for 3 weeks due to holidays.

Aart

Van: Giacomo Roversi [mailto:notifications@github.com]
Verzonden: donderdag 1 september 2016 17:24
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Comment
Onderwerp: Re: [overeem11/RAINLINK] invalid subscript type 'list' (#1)

Sorry for the multiple messages.
I have copied the code in the corresponding section of Run.R, but I do not have received any modified copy of Config.R or RainMapsRadarsTimeStep.R. Do I have to edit them with this informations or were they meant to be forwarded with the post?
Thank you for your time
Giacomo

**Comment by giacom0rovers1** [comment]
Sure, thanks. I write you an email in private
happy holidays

Giacomo

**Comment by giacom0rovers1** [comment]
Hi Aart,
I have isolated the source of the issue and with the help of a colleague we probably solved it, even though we do not understand why it was happening. 

The ScaleLow[p] call that fails is the one in the argument "fill" of aes( ) inside the geom_polygon( ) function that plots the colour scale if there is no data to plot.

```
if (dataf[1,1]==-99999999)
            {
                # To make sure that the colour scale is always plotted:
                polygondata = data.frame(c(999),c(999))
                names(polygondata) = c("polygonlon","polygonlat")       
                fig <- fig + geom_polygon(aes(x = polygonlon, y = polygonlat, fill = ScaleLow[p]), 
                data = polygondata, alpha=AlphaPolygon, col=PixelBorderCol, size=SizePixelBorder)   
            }
```

The index p here loops from 1 to 5 (i. e. `ColoursNumber`), and the break happens only the last time (p=5). We think there is no relation to the numerical value (five) because we extended the cycle from 1 to 6 and it happened again the last time (in that case p=6).

We found instead that assignig the value of ScaleLow[p] to a global variable
`prova <<- ScaleLow[p]`
and then using that variable as the 'fill' argument of aes( ) will fix the problem.

```
if (dataf[1,1]==-99999999)
    {
      # To make sure that the colour scale is always plotted:
      polygondata = data.frame(c(999),c(999))
      names(polygondata) = c("polygonlon","polygonlat")
      prova <<- ScaleLow[p]
      Fig <- Fig + geom_polygon(aes(x = polygonlon, y = polygonlat, fill = prova),
                                data = polygondata, alpha=AlphaPolygon, col=PixelBorderCol, size=SizePixelBorder)
    }
```

I have tested the RainMapsLinksTimeStep and RainMapsLinksDaily functions and it works for both.
We do not know  why during the last round of the loop the function rejects an argument if it is not set globally. We consider our fix an useful workaround but not a real solution. But at least, it works!

**Comment by overeem11** [comment]
Hi Giacomo,

Thanks for all the suggestions! I will incorporate them, hopefully by the end of October, but it can take a while since I have many other things to do.

Best,
Aart

---

Van: Giacomo Roversi [notifications@github.com]
Verzonden: vrijdag 23 september 2016 13:15
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Comment
Onderwerp: Re: [overeem11/RAINLINK] invalid subscript type 'list' (#1)

Hi Aart,
I have isolated the source of the issue and with the help of a colleague we probably solved it, even though we do not understand why it was happening.

The ScaleLow[p] call that fails is the one in the argument "fill" of aes( ) inside the geom_polygon( ) function that plots the colour scale if there is no data to plot.

if (dataf[1,1]==-99999999)
            {
                # To make sure that the colour scale is always plotted:
                polygondata = data.frame(c(999),c(999))
                names(polygondata) = c("polygonlon","polygonlat")
                fig <- fig + geom_polygon(aes(x = polygonlon, y = polygonlat, fill = ScaleLow[p]),
                data = polygondata, alpha=AlphaPolygon, col=PixelBorderCol, size=SizePixelBorder)
            }

The index p here loops from 1 to 5 (i. e. ColoursNumber), and the break happens only the last time (p=5). We think there is no relation to the numerical value (five) because we extended the cycle from 1 to 6 and it happened again the last time (in that case p=6).

We found instead that assignig the value of ScaleLow[p] to a global variable
prova <<- ScaleLow[p]
and then using that variable as the 'fill' argument of aes( ) will fix the problem.

if (dataf[1,1]==-99999999)
    {
      # To make sure that the colour scale is always plotted:
      polygondata = data.frame(c(999),c(999))
      names(polygondata) = c("polygonlon","polygonlat")
      prova <<- ScaleLow[p]
      Fig <- Fig + geom_polygon(aes(x = polygonlon, y = polygonlat, fill = prova),
                                data = polygondata, alpha=AlphaPolygon, col=PixelBorderCol, size=SizePixelBorder)
    }

I have tested the RainMapsLinksTimeStep and RainMapsLinksDaily functions and it works for both.
We do not know why during the last round of the loop the function rejects an argument if it is not set globally. We consider our fix an useful workaround but not a real solution. But at least, it works!

�
