### ISSUE TITLE
warn.conflicts in attach() call

### ISSUE THREAD

**Issue by giacom0rovers1** [overeem11/RAINLINK#2]
Hi Aart,

I get numerous warning messages about the object masking done by the 'attach()' function every loop of the interpolation process. It is about 72k rows for the data of the sample, which make the output reading uncomfortable. I also understand that the masking is not an issue but instead makes the code work properly.

So, can I suggest to add the "warn.conflicts = FALSE" option to the attach() function in the Interpolation.R file? It will completely suppress the warnings without altering the program.

`if (Variogram=="ClimVar"){`
`ParamVarModel <- ClimVarParam(DateStr = as.character(t[i]), TimeScaleHours = dt / 3600)`
`attach(ParamVarModel, warn.conflicts = FALSE)`
`Method <- "# Ordinary kriging interpolation. Climatological sill, range, and nugget."`
`}`

I already tried that myself and it works correctly, as you can see in the enclosed output file.

[Run.Rout2.txt](https://github.com/overeem11/RAINLINK/files/449694/Run.Rout2.txt)

Regards

Giacomo Roversi
Ferrara, Italy

**Comment by overeem11** [comment]
Hi Giacomo,

Thanks for the feedback! I will change it in the next version of RAINLINK.

Best regards,
Aart

---

Van: Giacomo Roversi [notifications@github.com]
Verzonden: donderdag 1 september 2016 15:17
Aan: overeem11/RAINLINK
Onderwerp: [overeem11/RAINLINK] warn.conflicts in attach() call (#2)

Hi Aart,

I get numerous warning messages about the object masking done by the 'attach()' function every loop of the interpolation process. It is about 72k rows for the data of the sample, which make the output reading uncomfortable. I also understand that the masking is not an issue but instead makes the code work properly.

So, can I suggest to add the "warn.conflicts = FALSE" option to the attach() function in the Interpolation.R file? It will completely suppress the warnings without altering the program.

if (Variogram=="ClimVar"){
ParamVarModel <- ClimVarParam(DateStr = as.character(t[i]), TimeScaleHours = dt / 3600)
attach(ParamVarModel, warn.conflicts = FALSE)
Method <- "# Ordinary kriging interpolation. Climatological sill, range, and nugget."
}

I already tried that myself and it works correctly, as you can see in the enclosed output file.

Run.Rout2.txthttps://github.com/overeem11/RAINLINK/files/449694/Run.Rout2.txt

Regards

Giacomo Roversi
Ferrara, Italy

�
